### ISSUE TITLE
我移植的时候遇到一个问题，不能加载库

### ISSUE THREAD

**Issue by renwfy** [qdrzwd/VideoRecorder#44]
Process: com.niusan.ctchaonao, PID: 21354
                                                                      java.lang.UnsatisfiedLinkError: Couldn't load checkneon from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.niusan.ctchaonao-51.apk"],nativeLibraryDirectories=[/data/app-lib/com.niusan.ctchaonao-51, /vendor/lib, /system/lib]]]: findLibrary returned null
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:358)
                                                                          at java.lang.System.loadLibrary(System.java:526)
                                                                          at com.niusan.ctchaonao.recorder.FFmpegRecorderActivity.<clinit>(FFmpegRecorderActivity.java:257)
                                                                          at java.lang.Class.newInstanceImpl(Native Method)
                                                                          at java.lang.Class.newInstance(Class.java:1208)
                                                                          at android.app.Instrumentation.newActivity(Instrumentation.java:1068)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2370)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1243)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5426)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by mankind-evolve** [comment]
我也是。不知道混淆怎么写

**Comment by renwfy** [comment]
我直接没混淆，现在又有一问题

Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libopencv_core.so" needed by "libjniopencv_core.so"; caused by library "libopencv_core.so" not found
                                                                        at java.lang.Runtime.loadLibrary(Runtime.java:364)
                                                                        at java.lang.System.loadLibrary(System.java:526)
                                                                        at com.googlecode.javacpp.Loader.loadLibrary(Loader.java:711)
                                                                        at com.googlecode.javacpp.Loader.load(Loader.java:586)
                                                                        at com.googlecode.javacpp.Loader.load(Loader.java:540)
                                                                        at com.googlecode.javacv.cpp.opencv_core.<clinit>(opencv_core.java:134)
                                                                        at java.lang.Class.classForName(Native Method) 
                                                                        at java.lang.Class.forName(Class.java:251) 
                                                                        at com.googlecode.javacpp.Loader.load(Loader.java:561) 
                                                                        at com.googlecode.javacpp.Loader.load(Loader.java:540) 
                                                                        at com.googlecode.javacv.cpp.opencv_core$CvArr.<clinit>(opencv_core.java:156) 
                                                                        at com.niusan.ctchaonao.activity.FFmpegRecorderActivity.handleSurfaceChanged(FFmpegRecorderActivity.java:1080) 
                                                                        at com.niusan.ctchaonao.activity.FFmpegRecorderActivity.access$2000(FFmpegRecorderActivity.java:76) 
                                                                        at com.niusan.ctchaonao.activity.FFmpegRecorderActivity$2.onPostExecute(FFmpegRecorderActivity.java:389) 
                                                                        at com.niusan.ctchaonao.activity.FFmpegRecorderActivity$2.onPostExecute(FFmpegRecorderActivity.java:358) 
                                                                        at android.os.AsyncTask.finish(AsyncTask.java:632) 
                                                                        at android.os.AsyncTask.access$600(AsyncTask.java:177) 
                                                                        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                        at android.os.Looper.loop(Looper.java:136) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5426) 
                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by renwfy** [comment]
跟极光推送的库有冲突啊，加了极光推送就提示不能加载  "libopencv_core.so"
